### PR TITLE
Mentimeter as a notebook quiz option

### PR DESCRIPTION
**Pull request by ruanvdmerwe**
A very simple example of how we can put in a [mentimeter](https://www.mentimeter.com/) multiple choice question within the notebooks. This will allow us to see in real time how many people have answered the question and what the overall score is within the group. 

Not ideal, especially if the question is more advanced, but it meets a bit of the requirements we mentioned in the meeting on Monday. 

Mentimeter also free.

To see how a question can be asked, go to www.menti.com and use the code 8371 2006

### CODE REVIEW

**Comment by KaleabTessera** [comment]
Hi @ruanvdmerwe , this looks really cool! 

Just not sure about the pricing - https://www.mentimeter.com/plans. Not sure how many questions we can ask per prac using this for free?

**Comment by ruanvdmerwe** [comment]
From what I can see, seems as though it can be 5 quiz slides per presentation, where number of presentations is unlimited.

**Comment by KaleabTessera** [comment]
@ruanvdmerwe So does this mean each prac can have 5 questions? Not sure if we can have multuple presentations in a prac so that we can have more questions? Do you think this is enough for each prac? What do you think @taliesinb? 

I also briefly looked at alternatives like Kahoots or PollEverywhere, but they seemed to have a limit on audience size and/or require an app. Are there other alternatives? https://github.com/jmshea/jupyterquiz looks promising 🤔

**Comment by ruanvdmerwe** [comment]
@KaleabTessera, each presentation can have 5 quizes and each person has unlimited presentations, so we can maybe make it a presentation per section (doubt more than 5 questions per section will be required). 

Will look a bit into Jupyterquiz as well, does look super nice.

**Comment by KaleabTessera** [comment]
@ruanvdmerwe After doing some thinking, I think the best option might be having an embed google forms assessment in each section. That will give us stats and scores, without people having leave the notebook. What do you think? 

Example of a quiz - https://docs.google.com/forms/d/e/1FAIpQLSdt8ezHE08XsvBJEVIR3C8E7bW0XT-MlRD7dz8bbQHn0mFjbg/viewform?usp=sf_link.

**Comment by ruanvdmerwe** [comment]
@KaleabTessera Agree with you, reduces the jumping around which just keeps it cleaner. Closing this PR :)

**Pull request closed without merging**
