### PR TITLE
Add 'deep generative models' prac

### PR DESCRIPTION
**Pull request by JamesAllingham**
This PR contains V1 of the deep generative models prac. 

There are still some very small TODOs:
1. Adding additional discussion and optional reading in various places.
2. Various standardisation/cleaning up tweaks, e.g.:
  * Adding difficulty tags (e.g., beginner, intermediate, advanced) to the various sections and tasks.
 3. Adding the final feedback form.
 4. Adding hints for the final tasks.

Nevertheless, let's get V1 merged and then I'll keep working on these TODOs this week :)

### CODE REVIEW

**Comment by ruanvdmerwe** [comment]
First impressions: seriously fun and cool prac :)

**Comment by JamesAllingham** [comment]
<p>Great suggestion, I'll do that.</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>Hehe, thanks!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>Thanks again!</p><p> </p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>Many thanks!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>My thanks, good sir!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>It turns out I should put this through spell check :D Or stop writing late at night :P Thanks, yet again!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>Hmmm, in my mind 4-6 and 12-20 are mostly just boilerplate code that don't add much value - but I'd be happy to be convinced otherwise. Why do you think that they will help drive home the formulas? (I think highlighting 51-53 is a great idea though!)</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>Gracias!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>xìe xìe!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<p>Done, that is nice!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ruanvdmerwe** [comment]
<p>Note to self: don't review late at night. I have no idea why I said 12-20 should be shown, that really is just boiler plate haha. </p><p> </p><p>4-6 can be shown just to see where x comes from for lines 51-53, but not really important. Only important ones are 51-53.</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JamesAllingham** [comment]
<blockquote>Note to self: don't review late at night.</blockquote><p>Lol, late night working can definitely make us a little crazy. I'm now putting all of my writing through Grammarly to avoid spelling and grammar mistakes :D </p><p> </p><p>Thanks for all the feedback!</p>

---

 <a href='https://app.reviewnb.com/deep-learning-indaba/indaba-pracs-2022/pull/15/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JavierAntoran** [comment]
Couldn't get reviewNB to work in my browser so I will add some comments here. Apologies for the inconvenience.

In the cat picture diffusion model example, y is not defined. As a consequence, I think people might be confused when you tell them to try to imagine the conditional distribution p(x|y). If you made the example about both cats and dogs then y could be cats and then it would be easier to imagine the distribution of just cat pictures. 


On the score function optimisation animation with sliders:
* There are many scattered points which are extraneous to the thing you are showing and can lead to confusion
* A question someone might have at this point is: given a large enough lr and step size, I will always end up at a mode of the density. In this case, I will only be able to draw 2 different samples, 1 per mode. How can we ensure that we draw samples from the distributions and not just the modes? Is there an assumption that p(x) is strongly multimodal and has a mode at each possible image? 
* in the pseudocode “core_fun” -> “score_fun”

**Comment by ruanvdmerwe** [comment]
Just some final comments:

* Get GAN explanation written before merging in, or leave it out.
* Yellow text in "building unet" unreadable when in light mode
* I have not looked at spelling or grammar again, but it does read very nicely
* The one thing which might throw people off, but which could be very good as well (so I am torn) is the exercises that do not have starting points at the end. I like it, but it is also hard. 
* I think the connection to EMB, VAE and Autoregressive section can be left as just resources to it. People will need to understand other methods to appreciate the section, so I think sending them down the rabbit hole is good enough. 

Lastly: AWESOME PRACTICAL and super well explained.

**Review by ruanvdmerwe — DISMISSED** [review]
Besides those minor comments and a final Grammarly pass, very good practical.

**Review by JavierAntoran — DISMISSED** [review]
Looks good to me. I have 2 comments:

* As recommended by @KaleabTessera, you can add `%%capture` at the beginning of the cell that pip-installs stuff to suppress the output
* The section where different types of DGMs are related to diffusion models is marked as TODO. However, I already wrote about a lot of those relationships a couple of cells up where the different types of DGMs are explained. Perhaps you can remove this section or move stuff from the earlier cell to here.

**Comment by JamesAllingham** [comment]
Hey @JavierAntoran and @ruanvdmerwe thanks for the feedback! I've incorporated your comments. 

Regarding the discussion of VAEs, etc. I've removed the section with TODOs and moved the whole discussion to the end of the prac so that folks don't get distracted going down a rabbit hole until after they have finished the main content. 

@ruanvdmerwe  regarding the tasks at the end being too difficult due to a lack of starting points, that was somewhat by design since I felt it was ok to have more open ended tasks at the end, given then more structured tasks throughout. However, I think a there is room for a compromise! I'll add some hints in the next PR. 

Could you both re-approve so that I can merge (since making the minor changes to address your comments made your approvals stale)? :)

**Review by ruanvdmerwe — APPROVED** [review]

**Pull request merged**
