### PR TITLE
Prac: Bayesian Deep Learning

### PR DESCRIPTION
**Pull request by JavierAntoran**
Prac is 90-95% complete. Would appreciate some feedback, especially from folks without experience in Bayesian ML.

### CODE REVIEW

**Comment by KaleabTessera** [comment]
Colab [Link](https://colab.research.google.com/github/deep-learning-indaba/indaba-pracs-2022/blob/prac-bayesian-deep-learning/Bayesian_Deep_Learning_Prac.ipynb) .

**Review by JamesAllingham — DISMISSED** [review]

**Review by KaleabTessera — DISMISSED** [review]
I went through parts 0 & 1, looks great! :rocket: :fire: I will look through other parts later.

**Review by JamesAllingham — APPROVED** [review]
LGTM!

**Review by KaleabTessera — APPROVED** [review]
Really well done! @JavierAntoran

**Pull request merged**
